# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # - - - - - Master - - - - - #

  config.vm.define "hadoop-master" do |master|

    master.vm.box = "debian/jessie64"
    master.vm.hostname = "hadoop-master"

    #master.ssh.guest_port = 2222

    master.vm.network "private_network", ip: "192.168.0.2"

    master.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "playbook-common.yml"
      #ansible.playbook = "playbook-master.yml"
    end

  end

  # - - - - - Slaves - - - - - #

  (1..2).each do |i|

    config.vm.define "hadoop-slave#{i}" do |slave|

      slave.vm.box = "debian/jessie64"
      slave.vm.hostname = "hadoop-slave#{i}"

      #slave.ssh.guest_port = 2222

      slave.vm.network "private_network", ip: "192.168.0.1#{i}"

      slave.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "playbook-common.yml"
        #ansible.playbook = "playbook-slaves.yml"
      end

    end

  end

end
